version: "3"

networks:
  intern:
    external: false

services:
  django:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    container_name: purBeurre_django_prod
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - intern

  postgres:
    image: "postgres:latest"
    container_name: purBeurre_postgres
    env_file:
      - ./.env
    networks:
      - intern
    volumes:
      - pgdb:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19-alpine
    container_name: purBeurre_nginx
    volumes:
      - ./static:/home/app/web/staticfiles
      - ./media:/home/app/web/mediafiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
    networks:
      - intern
    ports:
      - 80:80
volumes:
  pgdb:
