version: "3.7"
networks:
  intern:
    external: false

services:
  django:
    build:
      context: .
    container_name: purBeurre_django
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - intern

  postgres:
    image: "postgres:latest"
    container_name: purBeurre_postgres
    env_file:
      - ./.env
    networks:
      - intern
    volumes:
      - pgdb:/var/lib/postgresql/data
volumes:
  pgdb:
