version: "3"

networks:
  intern:
    external: false

services:
  web:
    build: .
    container_name: myapp_web
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - intern

  db:
    image: "postgres:latest"
    container_name: myapp_db
    env_file:
      - ./.env
    networks:
      - intern
    volumes:
      - pgdb:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19-alpine
    container_name: myapp_nginx
    volumes:
      - ./static:/home/app/web/staticfiles
      - ./media:/home/app/web/mediafiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - intern
    ports:
      - 80:80
volumes:
  pgdb:
