version: "3"
networks:
  intern:
    external: false
  extern:
    external: true

services:
  django:
    image: "${WEB_IMAGE}"
    command: gunicorn purBeurre.wsgi:application --bind 0.0.0.0:8000
    container_name: p11purbeurre_django
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - intern
    depends_on:
      - postgres
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    networks:
      - intern
      - extern
    labels:
      - traefik.http.routers.nameyourrouter.rule=Host(`p11purbeurre.christophe-dupin.com`)
      - traefik.http.routers.nameyourrouter.tls=true
      - traefik.http.routers.nameyourrouter.tls.certresolver=lets-encrypt
      - traefik.port=80
    depends_on:
      - django

  postgres:
    image: "postgres:latest"
    container_name: p11purbeurre_postgres_prod
    networks:
      - intern
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume:
