version: "3.7"

services:
  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    container_name: purbeurre_django
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    container_name: purbeurre_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
