version: "3"
services:
  django:
    image: "${WEB_IMAGE}"
    command: gunicorn purBeurre.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - django

  postgres:
    image: "postgres:latest"
    container_name: purbeurre_postgres_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume:
