# Generated by Django 3.1.2 on 2020-10-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201030_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lipide',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_lipide',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
