# Generated by Django 3.1.2 on 2020-10-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('url_page', models.URLField()),
                ('image_url', models.URLField()),
                ('image_nutrition_url', models.URLField()),
                ('nutrition_grade', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
                ('substitute_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='product.product')),
            ],
        ),
    ]
