name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      DJANGO_SETTINGS_MODULE: 'purBeurre.settings.ci'
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      SECRET_KEY: 'turtertertekrtjerktjerkt'

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
    - name: Create ssh key
      run: |
        mkdir -p ~/.ssh/
        cd ~/.ssh/
        chmod 777 ~/.ssh/
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > id_rsa.pub
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 664 ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
    - name: Deploy to production
      run: |
        ssh -tto StrictHostKeyChecking=no cdupin@157.245.249.94 " cd /home/cdupin/P10-django-app_purBeurre && source env/bin/activate && export DJANGO_SETTINGS_MODULE='purBeurre.settings.production' && git pull origin master && python3 manage.py collectstatic --noinput  && python3 manage.py makemigrations  && python3 manage.py migrate  && supervisorctl restart && exit" 
        
